apiVersion: v1
kind: Service
metadata:
  name: piano-db
  labels:
    app: piano-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: piano-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
