apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n-back-backend-prd
resources:
  - ../../base
images:
  - name: registry.lab.i-tems.com/items-app-n-back-backend
    newTag: "4cb2133"
