apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - networkpolicy.yaml
images:
  - name: registry.lab.i-tems.com/hive-capability-web
    newTag: 1087ca7
