apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meetup-scheduler-frontend-prd
resources:
  - ../../base
images:
  - name: registry.lab.i-tems.com/meetup-scheduler-frontend
    newTag: b2c4ee8
